[theme]
mode = "dark"
source = "wallpaper"

[theme.templates]
builtin_ids = ["alacritty", "btop", "gtk3", "gtk4", "helix", "niri", "qt"]
community_ids = ["zen-browser", "fastfetch", "fcitx5", "yazi"]

[wallpaper]
directory = "~/Pictures/Wallpaper"
automation.enabled = true

[backdrop]
enabled = true

[bar.default]
position = "left"
start = ["launcher", "clipboard", "workspaces"]
end = ["media", "tray", "notifications", "group:g1", "group:g2", "battery", "session"]

[[bar.default.capsule_group]]
id = "g1"
members = ["brightness", "volume"]
fill = "surface_variant"
padding = 6.0

[[bar.default.capsule_group]]
id = "g2"
members = ["network", "bluetooth"]
fill = "surface_variant"
padding = 6.0

[control_center]
hidden_tabs = ["weather"]

[weather]
enabled = false

[notification]
history_retention_hours = 3

[osd]
position = "bottom_center"
kinds = { keyboard_layout = false, media = false }

[shell]
lang = "zh-Hans"
polkit_agent = true
screen_time_enabled = true
launcher.categories = false
panel = { launcher_placement = "attached", session_placement = "floating", session_position = "bottom_center" }
